### ISSUE TITLE
Type loss on "any"

### ISSUE THREAD

**Issue by khaosdoctor** [nxcd/paradox#24]
As stated in #5 and #23 this is the issue where I address the "any" problem.

We are loosing the typings in the entity by casting everything to any. We need to find a better solution to this.

**Comment by rjmunhoz** [comment]
The thing is: we don't actually know the type here.

The only way we could solve this safelly would be to delegate the responsibility of updating the current state to the child class, which I don't think is a viable option.

Finally, inline casting removes type safety on that specific occasion (which isn't type safe by itself), while adding an index signature also does, but for the whole class **and** child classes.

**Comment by rjmunhoz** [comment]
Plus, we're not casting "everything", we're casting one value, and only in that statement.

**Comment by khaosdoctor** [comment]
We're casting everything, every property, as any. That's what I meant

**Comment by rjmunhoz** [comment]
Yeah, but only on that single use of it. We're not actually using the type there. Casting it to `any` event makes sense
