### ISSUE TITLE
Improve EventEntity.updateState performance

### ISSUE THREAD

**Issue by gustavopch** [nxcd/paradox#6]
This is the current implementation:
```ts
private updateState () {
  for (const propertyName of Object.keys(this.state)) {
    this[propertyName] = this.state[propertyName]
  }
}
```
Reading from `this.state` multiple times invokes the getter multiple times. I believe the following code would prevent that:
```ts
private updateState () {
  // Read once
  const state = this.state
  for (const propertyName of Object.keys(state)) {
    // Then use for free without re-invoking the getter
    this[propertyName] = state[propertyName]
  }
}
```
That comes with a bonus of better debuggability for the getter. Currently, because it is invoked multiple times, trying to use `console.log` to inspect values generate a lot of repeated stuff in the console.

**Comment by khaosdoctor** [comment]
This is really good addition, could you open a PR please?
